export const providerCatalog = [
  {
    id: 'recaptcha-v2',
    name: 'Google reCAPTCHA v2',
    status: 'ready-official-test',
    fixture: '/provider-tests/recaptcha.html',
    adapter: 'recaptcha-test-observer',
    automatedSolve: false,
    notes: 'Uses Google published test key; deterministic integration testing only.',
  },
  {
    id: 'hcaptcha',
    name: 'hCaptcha',
    status: 'ready-official-test',
    fixture: '/provider-tests/hcaptcha.html',
    adapter: 'hcaptcha-test-observer',
    automatedSolve: false,
    notes: 'Uses hCaptcha published always-pass integration-test key.',
  },
  {
    id: 'turnstile',
    name: 'Cloudflare Turnstile',
    status: 'ready-official-test',
    fixture: '/provider-tests/turnstile.html',
    adapter: 'turnstile-test-observer',
    automatedSolve: false,
    notes: 'Pass/fail dummy keys plus forced-interactive manual fixture.',
  },
  {
    id: 'aws-waf',
    name: 'AWS WAF CAPTCHA / Challenge',
    status: 'needs-owned-staging',
    fixture: null,
    adapter: null,
    automatedSolve: false,
    notes: 'Requires an AWS-owned staging app/WAF configuration before browser integration can be tested.',
  },
  {
    id: 'datadome',
    name: 'DataDome',
    status: 'needs-authorized-sandbox',
    fixture: null,
    adapter: null,
    automatedSolve: false,
    notes: 'No public deterministic test fixture is bundled.',
  },
  {
    id: 'perimeterx-human',
    name: 'HUMAN / PerimeterX',
    status: 'needs-authorized-sandbox',
    fixture: null,
    adapter: null,
    automatedSolve: false,
    notes: 'Adapter boundary reserved for an owned/authorized sandbox.',
  },
  {
    id: 'akamai-bot-manager',
    name: 'Akamai Bot Manager',
    status: 'needs-authorized-sandbox',
    fixture: null,
    adapter: null,
    automatedSolve: false,
    notes: 'Adapter boundary reserved for an owned/authorized sandbox.',
  },
];
